[database]
data_base_path = "./data"
db_path_file = "./data/electric_vehicle.duckdb"
db_path_in_memory = ":memory:"  # In-memory database for testing
db_path = "./data/electric_vehicle.duckdb"  # Default database path
table_name = "electric_vehicle_population"
chunk_size = 30000

[ingestion]
csv_file_path = "data/Electric_Vehicle_Population_Data.csv"
total_rows_sanity_check = 75215
reload_enabled = true

# Uncomment these lines if using the "light" version
# csv_file_path = "data/Electric_Vehicle_Population_Data_light.csv"
# total_rows_sanity_check = 9145

[analytics]
queries_path = "./queries"
verbose = true